### PR TITLE
Pixel mask by telnet command to Zynq and configuration parameter

### PR DESCRIPTION
**Pull request by lmarcelli**
Sorry, I made 2 pull request in few minutes. This second one is the one correct (I merged Corrado software).

### CODE REVIEW

**Comment by cescalara** [comment]
Hi!

So there are still conflicts to be resolved, I imagine it is due to my introduction of the third ARDUINO_DEBUG option, and perhaps some others things. Would you guys like to resolve the conflicts or shall I deal with it?

**Comment by lmarcelli** [comment]
If you can solve it, it's better.
I am now at Frascati Laboratory for the final integration of the focal
surface.

Let me know,

Laura


Il mar 21 mag 2019, 18:06 Francesca <notifications@github.com> ha scritto:

**Comment by cescalara** [comment]
No problem, I'll use the same approach as before and keep you updated. Could be a few days before I get around to it.

**Comment by lmarcelli** [comment]
If we decide to solve by ourselves, I'll write you.


Il mar 21 mag 2019, 18:13 Francesca <notifications@github.com> ha scritto:

**Comment by cescalara** [comment]
Hi guys, 

I'm working on resolving the conflicts and I see that you have the paths set up differently for the configuration files. 

For example, in ConfigManager.h you have:
`#define CONFIG_DIR "/home/minieuso_cpu/CPU/CPUsoftware/config"`

and I have:
`#define CONFIG_DIR "/home/software/CPU/CPUsoftware/config"`

I have set up the initialisation scripts and documentation/installation instructions around an installation of the software in `/home/software/` as this is what was originally decided. Would it be a problem for you to switch back to this? I think it would be easier than going through and modifying elsewhere in the code.

Let me know. I will continue with other conflicts for now.

**Comment by cescalara** [comment]
Also @Giammanco it looks like your text editor is adding characters to line endings? I attach a screenshot of the diff in my editor.
Screenshot 2019-05-24 at 18 08 15

**Comment by cescalara** [comment]
I closed the merge and have made a new release (7.9.0) with your updates. I recommend that you `git pull` this into your local version so we can start with the same code for new updates! I noticed that I was making some repeat resolutions form the previous merge, so please do this!

I have tested that the code compiles on my system but I leave to you to run more involved tests.

**Comment by Giammanco** [comment]
Yes it is so

Il ven 24 mag 2019, 18:09 Francesca <notifications@github.com> ha scritto:

**Pull request merged**
