### PR TITLE
Two threshold and ArduinoManager

### PR DESCRIPTION
**Pull request by lmarcelli**
Setted two thresholds and merged with ArduinoManager (used sensor n. …  …0, choice between sensors to be implemented in dummy.conf)

### CODE REVIEW

**Comment by lmarcelli** [comment]
Setted two thresholds and merged with ArduinoManager (used sensor n. …  …0, choice between sensors to be implemented in dummy.conf)

**Comment by cescalara** [comment]
Hi Laura, the build has failed in travis with issues in AnalogManager. Do we want to completely get rid of AnalogManager now?

**Comment by lmarcelli** [comment]
Yes, we can.

**Comment by cescalara** [comment]
Ok, I will handle this

**Pull request merged**
